;===================================================================================================
; Assembly Utilities Library
;
; Written By: Oded Cnaan (oded.8bit@gmail.com)
; Site: http://odedc.net 
; Licence: GPLv3 (see LICENSE file)
; Package: UtilLib
;
; Description: 
; Include this file to get access to the utilities library
;===================================================================================================

; Common definitions
TRUE        equ     1
FALSE       equ     0
NULL        equ     0

; Includes
include "UtilLib\util.asm"
include "UtilLib\string.asm"
include "UtilLib\math.asm"
include "UtilLib\file.asm"
include "UtilLib\print.asm"
include "UtilLib\sound.asm"
include "UtilLib\time.asm"
include "UtilLib\keys.asm"
include "UtilLib\mouse.asm"
include "UtilLib\mem.asm"
