;===================================================================================================
; Keyboard scan code
;
; Written By: Oded Cnaan (oded.8bit@gmail.com)
; Site: http://odedc.net 
; Licence: GPLv3 (see LICENSE file)
; Package: XXX
;
; Description: 
; Not including shift / ctrl / alt combinations
; See http://stanislavs.org/helppc/scan_codes.html
;===================================================================================================

        SC_A	            equ   1E61h	    
		SC_B	            equ   3062h	    
		SC_C	            equ   2E63h	    
		SC_D	            equ   2064h	    
		SC_E	            equ   1265h	    
		SC_F	            equ   2166h	    
		SC_G	            equ   2267h	    
		SC_H	            equ   2368h	    
		SC_I	            equ   1769h	    
		SC_J	            equ   246Ah	    
		SC_K	            equ   256Bh	    
		SC_L				equ   266Ch	    
		SC_M				equ   326Dh	    
		SC_N				equ   316Eh	    
		SC_O				equ   186Fh	    
		SC_P				equ   1970h	    
		SC_Q				equ   1071h	    
		SC_R				equ   1372h	    
		SC_S				equ   1F73h	    
		SC_T				equ   1474h	    
		SC_U				equ   1675h	    
		SC_V				equ   2F76h	    
		SC_W				equ   1177h	    
		SC_X				equ   2D78h	    
		SC_Y				equ   1579h	    
		SC_Z				equ   2C7Ah	    
	

		SC_1				equ   0231h	    
		SC_2				equ   0332h	    
		SC_3				equ   0433h	    
		SC_4				equ   0534h	    
		SC_5				equ   0635h	    
		SC_6				equ   0736h	    
		SC_7				equ   0837h	    
		SC_8				equ   0938h	    
		SC_9				equ   0A39h	    
		SC_0				equ   0B30h	    


		SC_F1				equ   3B00h
		SC_F2				equ   3C00h	    
		SC_F3				equ   3D00h	    
		SC_F4				equ   3E00h	    
		SC_F5				equ   3F00h	    
		SC_F6				equ   4000h	    
		SC_F7				equ   4100h	    
		SC_F8				equ   4200h	    
		SC_F9				equ   4300h	    
		SC_F10				equ   4400h	    
		SC_F11				equ   8500h	    
		SC_F12				equ   8600h	    
		
		SC_BackSpace		equ   0E08h
		SC_Del				equ   5300h     
		SC_DownArrow		equ   5000h      
		SC_End				equ   4F00h      
		SC_Enter			equ   1C0Dh      
		SC_Esc				equ   011Bh      
		SC_Home				equ   4700h      
		SC_Ins				equ   5200h      
		SC_Keypad5			equ   4C35h	 
		SC_KeypadAsterix    equ   372Ah	
		SC_KeypadMinus		equ   4A2Dh 
		SC_KeypadPlus		equ   4E2Bh  
		SC_KeypadSlash		equ   352Fh  
		SC_LeftArrow		equ   4B00h  
		SC_PgDn				equ   5100h  
		SC_PgUp				equ   4900h  
		SC_PrtSc			equ   7200h
		SC_RightArrow		equ   4D00h 
		SC_SpaceBar			equ   3920h  
		SC_Tab				equ   0F09h  
		SC_UpArrow			equ   4800h  